export const blogCategories = [
  "Monitoring",
  "Social media",
  "Analytics",
  "Web development",
  "Mobile",
  "Cases",
];
export const blogsData = [
  {
    title: "New dashboard design and much more",
    img: "rectangle_1.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "1",
  },
  {
    title: "9 Quick Tips To Keep Your Online Customers Happy",
    img: "rectangle_2.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "2",
  },
  {
    title: "6 Tips to Make A Small Business Website Effective",
    img: "rectangle_3.png",
    readTime: "15 min read",
    date: "November 01, 2021",
    id: "3",
  },
  {
    title: "How Do You Know When Your Site Is Down?",
    img: "rectangle_4.png",
    readTime: "15 min read",
    date: "November 01, 2021",
    id: "4",
  },
  {
    title: "Negative Impact of Website Downtime",
    img: "rectangle_5.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "5",
  },
  {
    title: "4 Big Reasons You Need an SSL Certificate",
    img: "rectangle_6.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "6",
  },
  {
    title: "New dashboard design and much more",
    img: "rectangle_7.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "7",
  },
  {
    title: "New dashboard design and much more",
    img: "rectangle_8.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "8",
  },
  {
    title: "New dashboard design and much more",
    img: "rectangle_9.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "9",
  },
  {
    title: "New dashboard design and much more",
    img: "rectangle_10.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "10",
  },
  {
    title: "New dashboard design and much more",
    img: "rectangle_11.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "11",
  },
  {
    title: "New dashboard design and much more",
    img: "rectangle_12.png",
    readTime: "10 min read",
    date: "November 01, 2021",
    id: "12",
  },
] 